/**
 * @file jPackage.js
 * 
 */
(function() {

	/* Loaded Packages */
	var pkgs = {};
	var rewriteHandlers = [], errors = [];
	var currPath = null;
	
	/* TODO: cross browser */
	var xml = new XMLHttpRequest();

	/* default settings */
	var params = {

		debug: true,
		method: 'GET',
		path: "",
		suffix: 'js'

	};

	/* jPackage Error Class */
	var jPackageError = function(path, msg, originalError) {

		this.path = path;
		this.message = msg;
		this.originalError = originalError;

	};

	/**
	 * jPackageError.loadAsScript()
	 * Since packages are fetched as text and compiled with new Function(text), debugging is hard, because we won't get any usable trace.
	 * So by calling jPackageError.loadAsScript() the package is being loaded via a script tag.
	 * We can then use the browser's console to find syntax errors
	 */
	jPackageError.prototype.loadAsScript = function() {

		this.script = this.script || document.createElement("script");

		this.script.language = "javascript";
		this.script.src = this.path;

		document.head.appendChild(this.script);
	
		return this;	
	}

	/**
	 * This will take the textual representation of the package and try to compile it via new Function()
	 * @param path path of the fetched package
	 * @param pkg pkg as text
	 * @return true on success, false otherwise
	 */
	var compile = function(path, pkg) {

		currPath = path;
		var ret = true;

		try {

			/* Compile Package */
			(new Function(pkg))();

		} catch(e) {

			errors.push(new jPackageError(path, "Failed to compile '" + path + "'", e));
			ret = false;

		}
		
		currPath = null;
		return ret;
	};

	
	/**
	 * Try to fetch a package via a path generated by the rewriteHandlers.
	 * If the fetch is successfull, skip remaining handlers and try to compile package
	 * @param pkg Name of the package to load
	 * @return true on comlete success (fetch and compile or package exists already), false otherwise
	 */
	var tryLoad = function(pkg) {

		/* Package already loaded, nothing to do */
		if(pkg in pkgs) return true;

		/* try each rewrite handler */
		for(var i = 0; i < rewriteHandlers.length; ++i) {

			/* generate path */
			var path = rewriteHandlers[i](params.path, pkg, params.suffix);

			try {
				/* prepare xmlrequest */
				xml.open(params.method, path, false);
				
				/* and process request */
				xml.send(null);

			} catch(e) {

				/* Resolve Error, Method Error, Cross origin etc. */
				errors.push(new jPackageError(path, "Failed to fetch '" + pkg + "' via '" + path + "'", e));
				continue;

			}

			/* Fetch was successfull. We won't try any other RewriteHandlers, either return true or false here  */
			if(xml.status == 200) {

				/* Compile Error ? */
				if(!compile(path, xml.responseText)) {

					return false;
				}

				return true;

			} else {

				/* Non successfule fetch, try next RewriteHandler if available */
				errors.push(new jPackageError(path, "Failed to fetch '" + path + "': " + xml.status + " " + xml.statusText, null));
				continue;

			}

		}

		/* No RewriteHandlers returned a valid jPackage URI */
		return false;
		
	};

	/**
	 * Fetch or register jPackage
	 * @param package Either a String or an Object that represents a jPackage.
	 */
	var jPackage = function(pkg) {

		/* Fetch jPackage */
		if(typeof pkg == "string") {
	
			/* Loaded already ? */
			if(!(pkg in pkgs)) {
				/* Try to fetch it */
				tryLoad(pkg);
			}

			return pkgs[pkg] || null;

		} else if(typeof pkg == 'object') { /* Register jPackage*/

			/* We need a name so we can store it */
			if(!pkg["name"]) return;

			/* If package has prerequisites, try to fetch them first*/
			if("requires" in pkg && typeof pkg.requires == 'object' && pkg.requires instanceof Array) {

				for(var i = 0; i < pkg.requires.length; ++i) {

					var skip = false;

					/* a requirement that looks like this package? is skippable (not really required, but preffered to be loaded before the package */
					var r = pkg.requires[i].replace(/\s*\?/, function() {

						skip = true;
						return "";

					});

					/* Package could not be loaded and is not skippable */
					if(!jPackage(r) && !skip) {
						errors.push(new jPackageError(currPath, "Failed to load required package '" + r + "' for Package '" + pkg.name + "'", null));
						return;
					}

				}

				
					
			}

			/* If Package provides an init function */
			if("init" in pkg && typeof pkg.init == 'function') {

				try {
					/* Try to call it */
					pkg.init.call(pkg);
					/* and set pkg.init to true so it cannot be init'd twice and the user can test for successfull initialisation */
					pkg.init = true;
				} catch(e) {
					
					/* Might be a syntax error in pkg.init(). Don't register Package */
					errors.push(new jPackageError(currPath, "Failed to init '" + pkg.name + "'", e));
					return;
				}
			}

			/* Register Package */
			pkgs[pkg.name] = pkg;

		}
	};

	/**
	 * Register a handler to rewrite package to URI
	 * @param handler callback
	 */
	jPackage.registerRewriteHandler = function(handler) {

		if(rewriteHandlers.indexOf(handler) < 0) rewriteHandlers.push(handler);
		return this;

	};

	/**
	 * Configure jpackage
	 * @param options Object of options to be set
	 */
	jPackage.config = function(options) {

		for(o in options) {
			params[o] = options[o];
		}
	
		return this;
	}

	/**
	 * Seal jPackage
	 * After configuring and registering all rewriteHandlers, jPackage can be sealed, so no script loaded later on can manipulate for example the path, or rewrite any url
	 */
	jPackage.seal = function() {

		jPackage.registerRewriteHandler = Function.prototype;
		jPackage.config = Function.prototype;
	
		return this;

	}

	/* Register main RewriteHandler. Will rewrite package a.b.c to [params.path]/a/b/c.[params.suffix] */
	jPackage.registerRewriteHandler(function(path, pkg, suffix) {

		pkg = pkg.replace(/\./g, "/");
		return (path ? path.replace(/\/*$/, '') + '/' : '') + pkg + "." + suffix.replace(/^\./, "");

	});

	/**
	 * @returns errors Object
	 */
	jPackage.errors = function() {
		return errors;
	};

	/* make jPackage unmodifyable */
	Object.defineProperty(window, "jPackage", { value: jPackage });
	
})();
